/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WriteupsIndexRouteImport } from './routes/writeups.index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as TipsIndexRouteImport } from './routes/tips.index'
import { Route as InvariantIndexRouteImport } from './routes/invariant.index'
import { Route as WriteupsSlugRouteImport } from './routes/writeups.$slug'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as TipsSlugRouteImport } from './routes/tips.$slug'
import { Route as InvariantSlugRouteImport } from './routes/invariant.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteupsIndexRoute = WriteupsIndexRouteImport.update({
  id: '/writeups/',
  path: '/writeups/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsIndexRoute = TipsIndexRouteImport.update({
  id: '/tips/',
  path: '/tips/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvariantIndexRoute = InvariantIndexRouteImport.update({
  id: '/invariant/',
  path: '/invariant/',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteupsSlugRoute = WriteupsSlugRouteImport.update({
  id: '/writeups/$slug',
  path: '/writeups/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsSlugRoute = TipsSlugRouteImport.update({
  id: '/tips/$slug',
  path: '/tips/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InvariantSlugRoute = InvariantSlugRouteImport.update({
  id: '/invariant/$slug',
  path: '/invariant/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invariant/$slug': typeof InvariantSlugRoute
  '/tips/$slug': typeof TipsSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/writeups/$slug': typeof WriteupsSlugRoute
  '/invariant/': typeof InvariantIndexRoute
  '/tips/': typeof TipsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/writeups/': typeof WriteupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invariant/$slug': typeof InvariantSlugRoute
  '/tips/$slug': typeof TipsSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/writeups/$slug': typeof WriteupsSlugRoute
  '/invariant': typeof InvariantIndexRoute
  '/tips': typeof TipsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/writeups': typeof WriteupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invariant/$slug': typeof InvariantSlugRoute
  '/tips/$slug': typeof TipsSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/writeups/$slug': typeof WriteupsSlugRoute
  '/invariant/': typeof InvariantIndexRoute
  '/tips/': typeof TipsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/writeups/': typeof WriteupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invariant/$slug'
    | '/tips/$slug'
    | '/tools/$slug'
    | '/writeups/$slug'
    | '/invariant/'
    | '/tips/'
    | '/tools/'
    | '/writeups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invariant/$slug'
    | '/tips/$slug'
    | '/tools/$slug'
    | '/writeups/$slug'
    | '/invariant'
    | '/tips'
    | '/tools'
    | '/writeups'
  id:
    | '__root__'
    | '/'
    | '/invariant/$slug'
    | '/tips/$slug'
    | '/tools/$slug'
    | '/writeups/$slug'
    | '/invariant/'
    | '/tips/'
    | '/tools/'
    | '/writeups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvariantSlugRoute: typeof InvariantSlugRoute
  TipsSlugRoute: typeof TipsSlugRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  WriteupsSlugRoute: typeof WriteupsSlugRoute
  InvariantIndexRoute: typeof InvariantIndexRoute
  TipsIndexRoute: typeof TipsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  WriteupsIndexRoute: typeof WriteupsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writeups/': {
      id: '/writeups/'
      path: '/writeups'
      fullPath: '/writeups/'
      preLoaderRoute: typeof WriteupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips/': {
      id: '/tips/'
      path: '/tips'
      fullPath: '/tips/'
      preLoaderRoute: typeof TipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invariant/': {
      id: '/invariant/'
      path: '/invariant'
      fullPath: '/invariant/'
      preLoaderRoute: typeof InvariantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writeups/$slug': {
      id: '/writeups/$slug'
      path: '/writeups/$slug'
      fullPath: '/writeups/$slug'
      preLoaderRoute: typeof WriteupsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips/$slug': {
      id: '/tips/$slug'
      path: '/tips/$slug'
      fullPath: '/tips/$slug'
      preLoaderRoute: typeof TipsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invariant/$slug': {
      id: '/invariant/$slug'
      path: '/invariant/$slug'
      fullPath: '/invariant/$slug'
      preLoaderRoute: typeof InvariantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvariantSlugRoute: InvariantSlugRoute,
  TipsSlugRoute: TipsSlugRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  WriteupsSlugRoute: WriteupsSlugRoute,
  InvariantIndexRoute: InvariantIndexRoute,
  TipsIndexRoute: TipsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  WriteupsIndexRoute: WriteupsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
